server:
  port: 8080

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
    application: spring




## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: org.sunyiwei.entity  # 注意：对应实体类的路径

management:
    endpoints:
        web:
        exposure:
            include: health,info,env,metrics,prometheus

